/**
 * Playwright Test Configuration
 * GrabDocs Testing - Group 5
 * 
 * This file controls how all Playwright tests are executed.
 * It sets the browser, timeouts, video recording, and authentication.
 */

// @ts-check
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({

  // Directory where all test files are located
  testDir: './tests',

  // Run tests in parallel within each file
  fullyParallel: true,

  // Prevent test.only from being committed to CI
  forbidOnly: !!process.env.CI,

  // No retries locally, 0 flaky tolerance
  retries: 0,

  // Run one test at a time to avoid conflicts
  workers: 1,

  // Generate an HTML report with pass/fail results and videos
  reporter: 'html',

  // Global timeout: each test gets 60 seconds to complete
  timeout: 60000,

  // Shared settings applied to every test
  use: {
    // Record a trace on first retry for debugging failures
    trace: 'on-first-retry',

    // Record video of every test (pass or fail) for demo purposes
    video: 'on',

    // Reuse saved login session so tests skip login and 2FA
    // Generated by running: node save-auth.js
    storageState: 'auth.json',
  },

  // Browser configuration — only running on Chromium (Google Chrome engine)
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
